import { Link } from 'react-router-dom';
import { ArrowLeft, Zap } from 'lucide-react';
import CodeExample from './CodeExample';

export default function BoltPage() {
  const instructionBlock = `Create a TypeScript API route that:
1. Imports the MoneyGraph client from @moneygraph/sdk
2. Initializes it with an API key from environment variables
3. Exposes a POST handler that triggers a payout
4. Returns structured JSON response

Important: Verify the exact SDK API against @moneygraph/sdk v2.0.2 documentation before implementing.`;

  return (
    <div className="min-h-screen py-12 px-4">
      <div className="max-w-4xl mx-auto">
        <Link to="/ai" className="inline-flex items-center text-cyan-400 hover:text-cyan-300 mb-8">
          <ArrowLeft className="w-4 h-4 mr-2" />
          Back to AI Overview
        </Link>

        <div className="flex items-center mb-6">
          <Zap className="w-12 h-12 text-cyan-400 mr-4" />
          <h1 className="text-5xl font-bold">
            <span className="gradient-text">MoneyGraph + Bolt.new</span>
          </h1>
        </div>

        <p className="text-xl text-gray-400 mb-12">
          Deploy MoneyGraph-powered applications instantly with Bolt.new
        </p>

        <div className="glass-strong rounded-xl p-8 mb-12">
          <h2 className="text-2xl font-bold mb-4">Quick Setup</h2>
          <ol className="space-y-4 text-gray-400">
            <li className="flex">
              <span className="w-8 h-8 rounded-full bg-cyan-500/20 border-2 border-cyan-400 flex items-center justify-center font-bold text-cyan-400 mr-3 flex-shrink-0">
                1
              </span>
              <span>Create a new project on Bolt.new</span>
            </li>
            <li className="flex">
              <span className="w-8 h-8 rounded-full bg-cyan-500/20 border-2 border-cyan-400 flex items-center justify-center font-bold text-cyan-400 mr-3 flex-shrink-0">
                2
              </span>
              <span>Install MoneyGraph SDK: <code className="text-cyan-400">npm install @moneygraph/sdk</code></span>
            </li>
            <li className="flex">
              <span className="w-8 h-8 rounded-full bg-cyan-500/20 border-2 border-cyan-400 flex items-center justify-center font-bold text-cyan-400 mr-3 flex-shrink-0">
                3
              </span>
              <span>Add <code className="text-cyan-400">MONEYGRAPH_API_KEY</code> to environment variables</span>
            </li>
            <li className="flex">
              <span className="w-8 h-8 rounded-full bg-cyan-500/20 border-2 border-cyan-400 flex items-center justify-center font-bold text-cyan-400 mr-3 flex-shrink-0">
                4
              </span>
              <span>Create API routes or functions using the SDK</span>
            </li>
          </ol>
        </div>

        <div className="glass rounded-xl p-6 mb-12">
          <h3 className="text-xl font-semibold mb-4">Prompt for Bolt</h3>
          <p className="text-gray-400 mb-4">
            You can paste this instruction into Bolt to guide the implementation:
          </p>
          <CodeExample language="text" code={instructionBlock} />
        </div>

        <div className="glass rounded-lg p-6 bg-yellow-500/10 border border-yellow-500/30">
          <p className="text-sm text-yellow-400">
            <strong>⚠️ Important:</strong> Always verify the code generated by Bolt against the actual
            <code className="mx-1">@moneygraph/sdk</code> API. Check import paths, method names, and parameter
            structures in the SDK documentation before deploying.
          </p>
        </div>
      </div>
    </div>
  );
}
